<h3> Author Request Form</h3>
<p> Want to add your blogs on our store? send us a request. submit this form you'll get a email. </p>
<form  method="post">  
<label> Author Name </label> 
 <input name="a_name" type="text">
 <label> Author Email <label>
  <input name="a_email" type="text">
  <label> Blog Name </label>
    <input name="blog_name" type="text">
    <input type="hidden" id="status" name="status" value="pending">

    <input type="submit" name="submit" value="Submit">
</form>